#!/bin/bash

if [ $# -eq 0 ]
  then
      echo "Commit message is required"
      exit 1
fi

echo "Invoking JBake"
~/.sdkman/candidates/jbake/current/bin/jbake -b

echo "Committing the files..."
git add .
git commit -m "$1"
git push

echo "Done!"
